#
#  Copyright (C) 2006-2018 Talend Inc. - www.talend.com
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

#
# Sample compose using Talend Component Kit Server and this repository docker image
#

version: '3'

services:
    talend_component_kit:
      image: ${TALEND_REGISTRY}/talend-component-kit:1.0.1-dev
      hostname: tacokit
      ports:
        - 10000:10000
      environment:
        CONSOLE_LOG_LEVEL: INFO
        MEECROWAVE_OPTS: >
          -Dhttp=10000
          -Dtalend.component.server.component.registry=/opt/talend/maven/component-registry.properties
          -Dtalend.component.server.maven.repository=/opt/talend/maven/repository
      volumes:
        - tacokit_maven:/opt/talend/maven

    talend_component_kit_connectors:
      image: ${TALEND_REGISTRY}/talend/connectors-se:1.0.0-dev
      command: tail -f /dev/null
      volumes:
        - tacokit_maven:/opt/talend/maven

volumes:
  tacokit_maven:
