package org.talend.components.mongo;

public enum ConnectionAttributes {
    MAINTENANCE_FREQUENCY,
    MAINTENANCE_INITIAL_DELAY,
    MAX_CONNECTING,
    MAX_CONNECTION_IDLE_TIME,
    MAX_CONNECTION_LIFE_TIME,
    MAX_SIZE,
    MIN_SIZE,
    MAX_WAIT_TIME,
    LOCAL_THRESHOLD,
    REQUIRED_REPLICA_SET_NAME,
    SERVER_SELECTION_TIMEOUT,
    SRV_HOST,
    SRV_MAX_HOSTS,
    SRV_SERVICE_NAME,
    HEARTBEAT_FREQUENCY,
    MIN_HEARTBEAT_FREQUENCY,
    SOCKET_CONNECT_TIMEOUT,
    SOCKET_READ_TIMEOUT,
    RECEIVE_BUFFER_SIZE,
    SEND_BUFFER_SIZE
}
